# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Auth:   export LINODE_TOKEN=<token> (the provider reads it).
# Start:  terraform -chdir=.isoloom/cloud-vm/linode init && terraform -chdir=.isoloom/cloud-vm/linode apply \
#           -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/linode destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

variable "region" {
  type    = string
  default = "fr-par"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machines (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machines up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machines down after this many minutes (0: never)"
}

variable "expires_at" {
  type        = string
  default     = ""
  description = "When the environment should end, in Unix seconds (empty: no end), as a tag on every resource so a reaper can find what to destroy"
}

provider "linode" {}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-unguard-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
}

# The environment's one network: a VPC with a subnet at its exact range, so every machine keeps
# its address (10.60.124.0/24).
resource "linode_vpc" "env" {
  label  = local.name
  region = var.region
}

resource "linode_vpc_subnet" "env" {
  vpc_id = linode_vpc.env.id
  label  = "lab"
  ipv4   = "10.60.124.0/24"
}

resource "linode_firewall" "env" {
  label           = local.name
  inbound_policy  = "DROP"
  outbound_policy = "ACCEPT"
  inbound {
    label    = "ssh"
    action   = "ACCEPT"
    protocol = "TCP"
    ports    = "22"
    ipv4     = [var.allowed_cidr]
  }
  inbound {
    label    = "vpc-tcp"
    action   = "ACCEPT"
    protocol = "TCP"
    ports    = "1-65535"
    ipv4     = ["10.60.124.0/24"]
  }
  inbound {
    label    = "vpc-udp"
    action   = "ACCEPT"
    protocol = "UDP"
    ports    = "1-65535"
    ipv4     = ["10.60.124.0/24"]
  }
  inbound {
    label    = "vpc-icmp"
    action   = "ACCEPT"
    protocol = "ICMP"
    ipv4     = ["10.60.124.0/24"]
  }
  linodes = [linode_instance.unguard.id]
}

resource "random_password" "unguard" {
  length      = 24
  special     = false
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
}

resource "linode_instance" "unguard" {
  label           = "${local.name}-unguard"
  region          = var.region
  type            = "g6-standard-4"
  image           = "linode/ubuntu24.04"
  authorized_keys = [trimspace(var.ssh_public_key)]
  root_pass       = random_password.unguard.result
  booted          = true
  tags            = concat(["isoloom", "unguard", local.name], var.expires_at == "" ? [] : ["isoloom-expires-${var.expires_at}"])
  metadata {
    user_data = base64encode(var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : "")
  }
  interface {
    purpose = "public"
  }
  interface {
    purpose   = "vpc"
    subnet_id = linode_vpc_subnet.env.id
    ipv4 {
      vpc = "10.60.124.10"
    }
  }
}

resource "terraform_data" "unguard" {
  triggers_replace = [linode_instance.unguard.id]
  connection {
    type        = "ssh"
    host        = one(linode_instance.unguard.ipv4)
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "command -v sudo >/dev/null || (apt-get update -qq && apt-get install -y -qq sudo)", "sudo mkdir -p /opt/isoloom && sudo chown root /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-unguard.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-unguard.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/k3s.sh'",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/unguard.sh'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [linode_firewall.env]
}

output "machines" {
  value = {
    unguard = one(linode_instance.unguard.ipv4)
  }
}

output "ssh_users" {
  value = {
    unguard = "root"
  }
}

output "ip" {
  value = one(linode_instance.unguard.ipv4)
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}
