# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/cloud-vm/gcp init && terraform -chdir=.isoloom/cloud-vm/gcp apply \
#           -var billing_account=<id> -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/gcp destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 8.0"
    }
  }
}

variable "project" {
  type        = string
  default     = ""
  description = "An existing project; or leave empty and give billing_account for a project of its own"
}
variable "billing_account" {
  type        = string
  default     = ""
  description = "With no project: create one for this environment, billed here, deleted with it"
}
variable "org_id" {
  type    = string
  default = ""
}
variable "region" {
  type    = string
  default = "europe-west9"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machines (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machines up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machines down after this many minutes (0: never)"
}

provider "google" {
  region = var.region
}

# A project of its own when none is given: everything goes when the environment is destroyed.
resource "google_project" "env" {
  count               = var.project == "" ? 1 : 0
  name                = "isoloom-unguard"
  project_id          = "isoloom-${terraform_data.id.output}"
  billing_account     = var.billing_account
  org_id              = var.org_id == "" ? null : var.org_id
  deletion_policy     = "DELETE"
  auto_create_network = false
}

resource "google_project_service" "compute" {
  count              = var.project == "" ? 1 : 0
  project            = google_project.env[0].project_id
  service            = "compute.googleapis.com"
  disable_on_destroy = false
}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name    = "isoloom-unguard-${terraform_data.id.output}"
  root    = abspath("${path.module}/../../..")
  project = var.project != "" ? var.project : google_project_service.compute[0].project
  zone    = "${var.region}-a"
}

# The environment's networks: one VPC, a subnetwork per network with its exact range.
resource "google_compute_network" "env" {
  project                 = local.project
  name                    = local.name
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "lab" {
  project       = local.project
  name          = "${local.name}-lab"
  network       = google_compute_network.env.id
  ip_cidr_range = "10.60.124.0/24"
  region        = var.region
}

# Machine `unguard`: what may reach it.
resource "google_compute_firewall" "unguard_net" {
  project       = local.project
  name          = "${local.name}-unguard-net"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = ["10.60.124.0/24"]
  target_tags   = ["${local.name}-unguard"]
  allow {
    protocol = "all"
  }
}

resource "google_compute_firewall" "unguard_ssh" {
  project       = local.project
  name          = "${local.name}-unguard-ssh"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = [var.allowed_cidr]
  target_tags   = ["${local.name}-unguard"]
  allow {
    protocol = "tcp"
    ports    = ["22"]
  }
}

resource "google_compute_instance" "unguard" {
  project      = local.project
  name         = "${local.name}-unguard"
  machine_type = "e2-standard-2"
  zone         = local.zone
  tags         = ["${local.name}-unguard"]
  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2404-lts-amd64"
      size  = 40
    }
  }
  network_interface {
    subnetwork = google_compute_subnetwork.lab.id
    network_ip = "10.60.124.10"
    access_config {}
  }
  metadata = {
    ssh-keys = "ubuntu:${var.ssh_public_key}"
  }
  metadata_startup_script = var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : null
  labels = {
    "isoloom-environment" = "unguard"
    "managed-by"          = "isoloom"
  }
}

resource "terraform_data" "unguard" {
  triggers_replace = [google_compute_instance.unguard.id]
  connection {
    type        = "ssh"
    host        = google_compute_instance.unguard.network_interface[0].access_config[0].nat_ip
    user        = "ubuntu"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown ubuntu /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-unguard.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-unguard.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/k3s.sh'",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/unguard.sh'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
}

output "machines" {
  value = {
    unguard = google_compute_instance.unguard.network_interface[0].access_config[0].nat_ip
  }
}

output "ssh_users" {
  value = {
    unguard = "ubuntu"
  }
}

output "ip" {
  value = google_compute_instance.unguard.network_interface[0].access_config[0].nat_ip
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}
